=== edwardwang1/artisynth_core/artisynth/core/modelmenu/modelmenu.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.artisynth.org"
	xmlns="http://www.artisynth.org" elementFormDefault="unqualified">

	<xs:annotation>
		<xs:documentation>
			XML Schema for the ArtiSynth "Models" menu
		</xs:documentation>
	</xs:annotation>

	<!-- Elements -->
	<xs:element name="ModelMenu" type="rootType" />
	<xs:element name="menu" type="menuType" />
	<xs:element name="model" type="modelType" />
	<xs:element name="package" type="packageType" />
	<xs:element name="demosFile" type="demosFileType" />
	<xs:element name="separator" type="separatorType" />
	<xs:element name="label" type="labelType" />
	<xs:element name="include" type="includeType" />
	<xs:element name="hidden" type="hiddenType" />
	<xs:element name="history" type="historyType" />

	<!-- Element Types -->
	<xs:complexType name="rootType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="menu" />
			<xs:element ref="model" />
			<xs:element ref="package" />
			<xs:element ref="demosFile" />
			<xs:element ref="separator" />
			<xs:element ref="label" />
			<xs:element ref="include"/>
			<xs:element ref="hidden"/>
			<xs:element ref="history"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="hiddenType">
		<xs:complexContent>
			<xs:extension base="rootType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="menuType">
		<xs:complexContent>
			<xs:extension base="rootType">
				<xs:attribute name="text" type="xs:string" use="required" />
				<xs:attribute name="icon" type="xs:anyURI" use="optional" />
				<xs:attributeGroup ref="fontAttr" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="modelType">
		<xs:attribute name="class" type="javaType" use="required" />
		<xs:attribute name="text" type="xs:string" use="optional" />
		<xs:attribute name="icon" type="xs:anyURI" use="optional" />
		<xs:attribute name="args" type="xs:string" use="optional" />
		<xs:attributeGroup ref="fontAttr" />
	</xs:complexType>

	<xs:complexType name="packageType">
		<xs:attribute name="source" type="javaType" use="required" />
		<xs:attribute name="base" type="javaType"
			default="artisynth.core.workspace.RootModel" use="optional" />
		<xs:attribute name="args" type="xs:string" use="optional" />
		<xs:attribute name="regex" type="xs:string" use="optional" />
		<xs:attribute name="view" type="viewType" default="hierarchical"
			use="optional" />
		<xs:attribute name="compact" type="compactType" default="0"
			use="optional" />
		<xs:attributeGroup ref="fontAttr" />
	</xs:complexType>

	<xs:complexType name="demosFileType">
		<xs:attribute name="file" type="xs:anyURI" use="required" />
		<xs:attribute name="args" type="xs:string" use="optional" />
		<xs:attributeGroup ref="fontAttr" />
	</xs:complexType>

	<xs:complexType name="separatorType">
	</xs:complexType>

	<xs:complexType name="labelType">
		<xs:attribute name="text" type="xs:string" use="required" />
		<xs:attribute name="icon" type="xs:anyURI" use="optional" />
		<xs:attributeGroup ref="fontAttr"/>
	</xs:complexType>
	
	<xs:complexType name="includeType">
		<xs:attribute name="file" type="xs:anyURI" use="required" />
	</xs:complexType>
	
	<xs:complexType name="historyType">
		<xs:attribute name="size" type="positiveIntegerType" default = "4" 
			use="optional" />
		<xs:attribute name="compact" type="compactType" default="0"
			use="optional" />
		<xs:attributeGroup ref="fontAttr" />
	</xs:complexType>

	<!-- Attributes Types -->
	<xs:attributeGroup name="fontAttr">
		<xs:attribute name="fontname" type="xs:string" use="optional" />
		<xs:attribute name="fontstyle" type="xs:string" use="optional" />
		<xs:attribute name="fontsize" type="xs:integer" use="optional" />
	</xs:attributeGroup>

	<!-- Attribute Restrictions -->
	<xs:simpleType name="javaType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9\._])*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="viewType">
		<xs:restriction base="xs:string">
			<xs:pattern value="flat|hierarchical" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="compactType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="2" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="positiveIntegerType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>


</xs:schema>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/jawtonguedemos.xml
<?xml version="1.0" encoding="UTF-8"?>
<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">
	
	<model text="Badin Jaw" class="artisynth.models.jawTongue.BadinJawHyoid" />
	<model text="Badin Jaw-Hyoid-Tongue (Line)" class="artisynth.models.jawTongue.BadinJawHyoidTongue" />
	<model text="Badin Jaw-Hyoid-Tongue (FEM)" class="artisynth.models.jawTongue.JawHyoidFemMuscleTongue" />
	<model text="Badin Jaw-Tongue-Face" class="artisynth.models.face.BadinJawTongueFaceDemo" />
	<model text="Jaw" class="artisynth.models.dynjaw.JawDemo" />
	<model text="Jaw-Larynx" class="artisynth.models.dynjaw.JawLarynxDemo" />
	<model text="JawTongueSoftPalate" class="artisynth.models.palate.SoftPalateModel" />
	<model text="Hemimandibulectomy" class="artisynth.models.dynjaw.JawHemi" />
	<model text="Plane-Constrained Jaw" class="artisynth.models.mechdemos.PlaneConstrainedJaw" />
	<model text="Teeth Contact" class="artisynth.models.dynjaw.JawTeethContact" />
	<model text="Tongue (Line)" class="artisynth.models.tongue3d.HexTongueDemo" />
	<model text="Tongue (FEM)" class="artisynth.models.tongue3d.FemMuscleTongueDemo" />
	<model text="Dang Tongue" class="artisynth.models.dangTongue.FemTongueDemo" /> 

</ModelMenu>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/demos_flat.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Flat display of all the demo models -->
<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">

	<label text=" FEM" fontstyle="italic" />
	<include file="src/artisynth/core/modelmenu/femdemos.xml" />
	<separator />
	<label text=" Jaw/Tongue" fontstyle="italic" />
	<include file="src/artisynth/core/modelmenu/jawtonguedemos.xml" />
	<separator />
	<label text=" Inverse" fontstyle="italic" />
	<include file="src/artisynth/core/modelmenu/inversedemos.xml" />
	<separator />
	<label text=" Mech" fontstyle="italic" />
	<include file="src/artisynth/core/modelmenu/mechdemos.xml" />
	<separator />
	<label text=" Misc" fontstyle="italic" />
	<include file="src/artisynth/core/modelmenu/miscdemos.xml" />
</ModelMenu>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/femdemos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- FEM demos -->
<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">

	<model text="Articulated" class="artisynth.demos.fem.ArticulatedFem" />
	<model text="Beam (Tet)" class="artisynth.demos.fem.TetBeam3d" />
	<model text="Beam (Hex)" class="artisynth.demos.fem.HexBeam3d" />
	<model text="Block (Tet)" class="artisynth.demos.fem.Fem3dBlock" />
	<model text="Block (Hex)" class="artisynth.demos.fem.Hex3dBlock" />
	<model text="Collision" class="artisynth.demos.fem.FemCollision" />
	<model text="Simple Collision" class="artisynth.demos.fem.SimpleCollide" />
	<model text="Self Collision" class="artisynth.demos.fem.SelfCollision" />	
	<model text="Coupled Solve" class="artisynth.demos.fem.CoupledSolveDemo" />
	<model text="Fish" class="artisynth.demos.fem.FishDemo" />
	<model text="Hex Frame" class="artisynth.demos.fem.HexFrame" />
	<model text="Hydrostat" class="artisynth.demos.fem.HydrostatDemo" />
	<model text="Muscle" class="artisynth.demos.fem.FemMuscleDemo" />
	<model text="Muscle Arm" class="artisynth.demos.fem.FemMuscleArm" />
	<model text="Muscle Beam" class="artisynth.demos.fem.FemMuscleBeam" />
	<model text="Muscle Block" class="artisynth.demos.fem.FemMuscleBlock" />
	<model text="Simple Muscle" class="artisynth.demos.fem.SpongeDemo" />
	<model text="Plane-Constrained" class="artisynth.demos.fem.PlaneConstrainedFem" />
	<model text="Quadratic Tet Tube" class="artisynth.demos.fem.QuadtetTube" />
	
</ModelMenu>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/mechdemos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Mech-System demos -->
<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">
	<model text="Frame-Spring" class="artisynth.demos.mech.FrameSpringDemo" />	
	<model text="Layman" class="artsiynth.demos.mech.LaymanDemo" />
	<model text="MechModel" class="artisynth.demos.mech.MechModelDemo" />
	<model text="MechModel Collision" class="artisynth.demos.mech.MechModelCollide" />
	<model text="Multi-Point Spring" class="artisynth.demos.mech.MultiSpringDemo" />
	<model text="Point Force" class="artisynth.demos.mech.PointForceDemo" />	
	<model text="Puppet" class="artisynth.demos.mech.PuppetDemo" />
	<model text="Rigid Body Springs" class="artisynth.demos.mech.RigidBodyDemo" />
	<model text="Rigid Body Collision" class="artisynth.demos.mech.RigidBodyCollision" />
	<model text="Spring Mesh" class="artisynth.demos.mech.SpringMeshDemo" />
	<model text="Segmented Planes" class = "artisynth.demos.mech.SegmentedPlaneDemo" />
	
</ModelMenu>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/samplemenu.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- This is a sample menu that demonstrates the capabilities of this XML 
	menu format. 
	Enable this demos menu with the command-line option "-demosMenu	<filename>" 
	-->

<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">

	<menu text="Distribution" icon="src/artisynth/core/gui/icon/artisynth16.gif">
		<!-- loads a regular .demoModes file and places models in the current submenu -->
		<demosFile file=".demoModels" />
	</menu>

	<menu text="Mech Demos">
		<include file="mechdemos.xml" />
	</menu>

	<menu text="OpenSim">
		<!-- explicitly define models -->
		<model text="OpenSim Arm Demo" class="artisynth.models.opensim.ArmDemo" />
		<model text="OpenSim Arm Inverse" class="artisynth.models.opensim.ArmInv" />
	</menu>
	
	<!-- A menu separator -->
	<separator />

	<menu text="Models in artisynth.models">
		<!-- searches for and includes all RootModels in artisynth.models -->
		<package source="artisynth.models" view="hierarchical" />
	</menu>
	<menu text="    ''    (compact)">
		<!-- creates a more compact menu by merging submenus containing only one 
			entry with its parent -->
		<package source="artisynth.models" view="hierarchical"
			compact="1" />
	</menu>
	<menu text="    ''    (super compact)">
		<!-- same as before but shortens the titles -->
		<package source="artisynth.models" view="hierarchical"
			compact="2" />
	</menu>
	<menu text="'JawDemo' Models (flat)">
		<!-- Finds all classes that inherit from 'JawDemo' and displays in a flat 
			structure -->
		<package source="artisynt.models" base="JawDemo" view="flat"
			compact="0" />
	</menu>
	<menu text="    ''    (flat, compact)">
		<package source="artisynth.models" base="JawDemo" view="flat"
			compact="1" />
	</menu>
	<menu text="    ''    (flat, super compact)">
		<package source="artisynth.models" base="artisynth.models.dynjaw.JawDemo"
			view="flat" compact="2" />
	</menu>

	<separator />
	<model text="myCF Loader" icon="src/artisynth/core/gui/icon/mycf16.gif"
		class="artisynth.models.myCF.Loader" />
	<model text="&quot;HyperSkin&quot; Demo" class="artisynth.models.mechdemos.HyperSkinDemo" />
</ModelMenu>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/demos_hierarchical.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Hierarchical display of all the demo models -->
<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">

	<menu text="FEM">
		<include file="src/artisynth/core/modelmenu/femdemos.xml" />
	</menu>
	<menu text="Jaw/Tongue">
		<include file="src/artisynth/core/modelmenu/jawtonguedemos.xml" />
	</menu>
	<menu text="Inverse">
		<include file="src/artisynth/core/modelmenu/inversedemos.xml" />
	</menu>

	<menu text="Mech">
		<include file="src/artisynth/core/modelmenu/mechdemos.xml" />
	</menu>

	<menu text="Miscellaneous" >
		<include file="src/artisynth/core/modelmenu/miscdemos.xml" />
	</menu>
</ModelMenu>

=== edwardwang1/artisynth_core/artisynth/core/modelmenu/miscdemos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Misc. demos -->
<ModelMenu xmlns="http://www.artisynth.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.artisynth.org modelmenu.xsd">
	
	<model text="Articulator" class="artisynth.models.articulator.ArticulatorDemo" />
	<model text="Dental Casts" class="artisynth.models.articulator.DentalDemo" />
	<model text="Kura Face" class="artisynth.models.kuraFace.KuraFaceModelRoot" />
	<model text="Badin Face" class="artisynth.models.face.BadinFaceDemo" />
	<model text="Badin FEM-Muscle Face" class="artisynth.models.face.BadinFemMuscleFaceDemo" />
	<model text="Reference Face" class="artisynth.models.face.RefFaceDemo" />
	<model text="Reference FEM-Muscle Face" class="artisynth.models.face.RefFemMuscleFaceDemo" />
	<model text="Rat Leg" class="artisynth.models.ratLeg.RatLeg" />
	<model text="Soft Palate" class="artisynth.models.palate.SoftPalateDemo" />
	<model text="Vocal-Nasal Tract" class="artisynth.models.tubesounds.VTNTDemo" />
	<model text="VH Larynx" class="artisynth.models.larynx.VHLarynxDemo" />

</ModelMenu>
